# Generated by Django 3.0.4 on 2020-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(max_length=2)),
                ('minutes', models.IntegerField(max_length=2)),
                ('slot', models.IntegerField()),
            ],
        ),
    ]
